// Write a javascript program to pretend to look like a hacker
// Try to emulate a terminal using javascript logic and it should look to others as if you are hacking a system
// Try to display messages like:
        // Initializing Network
        // Connecting to service...
        // Retreiving username...
        // Username found....
        // Trying a combination of 4.5 Trillion passwords...
        // Password found...
        // Connecting to Facebook...

// Fool your friends into thinking that you are a hacker and have fun
// PROTIP: Try to use a green text on a black background